import type { BusinessContext } from "@/lib/types";
import { generateSocialPost, generateCarousel } from "./social";
import { generateVideoScript } from "./video";
import { generateEmail, generateBlogPost, generateQuoteCta } from "./writing";
import { everythingPackageSchema, type EverythingPackage } from "../schemas";

/**
 * The "Create Everything" engine: takes one idea and fans it out into every
 * major content format in parallel, then assembles the package. Each piece
 * is generated by its own focused call (rather than one giant JSON blob) so
 * quality stays high and no single response risks truncation.
 */
export async function generateEverythingPackage(
  ctx: BusinessContext,
  idea: string
): Promise<EverythingPackage> {
  const [
    facebookPost,
    instagramCaption,
    instagramCarousel,
    tiktokScript,
    reelsScript,
    youtubeShortScript,
    linkedinPost,
    email,
    blogPost,
    quoteCta,
  ] = await Promise.all([
    generateSocialPost(ctx, { platform: "facebook", topic: idea }),
    generateSocialPost(ctx, { platform: "instagram", topic: idea }),
    generateCarousel(ctx, { topic: idea }),
    generateVideoScript(ctx, { topic: idea, platform: "TikTok", lengthLabel: "30-60 seconds" }),
    generateVideoScript(ctx, { topic: idea, platform: "Instagram Reels", lengthLabel: "30-60 seconds" }),
    generateVideoScript(ctx, { topic: idea, platform: "YouTube Shorts", lengthLabel: "30-60 seconds" }),
    generateSocialPost(ctx, { platform: "linkedin", topic: idea }),
    generateEmail(ctx, { topic: idea }),
    generateBlogPost(ctx, { topic: idea }),
    generateQuoteCta(ctx, { topic: idea }),
  ]);

  const assembled: EverythingPackage = {
    idea,
    facebookPost,
    instagramCaption,
    instagramCarousel,
    tiktokScript,
    reelsScript,
    youtubeShortScript,
    linkedinPost,
    email,
    blogPost,
    quoteGraphicText: quoteCta.quote,
    cta: quoteCta.cta,
    imagePrompt: quoteCta.imagePrompt,
  };

  return everythingPackageSchema.parse(assembled);
}
